# Generated by Django 4.2.2 on 2023-11-26 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_sell_delete_medicines'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medicines',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicine_name', models.CharField(max_length=250)),
                ('medicine_image', models.ImageField(blank=True, null=True, upload_to='products')),
                ('medicine_price', models.IntegerField()),
                ('medicine_descripton', models.TextField()),
                ('medicine_exp', models.DateField()),
            ],
        ),
        migrations.DeleteModel(
            name='Sell',
        ),
    ]
