# Generated by Django 4.2.2 on 2024-06-01 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_sell_sell_by_sell_sell_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerprofile',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
