# Generated by Django 4.2.2 on 2024-06-02 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_customerprofile_latitude_customerprofile_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='sell',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sell',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
