# Generated by Django 4.2.2 on 2024-06-02 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_sell_latitude_sell_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerprofile',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='farmerprofile',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
