# Generated by Django 4.2.2 on 2024-11-20 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_customerprofile_status_farmerprofile_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerprofile',
            name='role',
            field=models.CharField(default='Unknown', max_length=250),
        ),
        migrations.AddField(
            model_name='farmerprofile',
            name='role',
            field=models.CharField(default='Unknown', max_length=250),
        ),
    ]
