# Generated by Django 4.2.2 on 2024-11-20 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_customerprofile_role_farmerprofile_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerprofile',
            name='role',
            field=models.CharField(default='customer', max_length=250),
        ),
        migrations.AlterField(
            model_name='farmerprofile',
            name='role',
            field=models.CharField(default='farmer', max_length=250),
        ),
    ]
