# Generated by Django 4.2.2 on 2024-11-20 16:10

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_alter_customerprofile_role_alter_farmerprofile_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='productitems',
            name='unique_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
