# Generated by Django 4.2.2 on 2024-11-21 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_productitems_unique_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='sell',
            name='sell_exp',
            field=models.DateField(default='2024-12-31'),
        ),
    ]
