# Generated by Django 4.2.2 on 2024-11-21 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_sell_sell_exp'),
    ]

    operations = [
        migrations.CreateModel(
            name='myCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('items', models.CharField(max_length=1500)),
                ('quantity', models.CharField(max_length=100)),
                ('price', models.CharField(max_length=100)),
                ('status', models.BooleanField(default=True, max_length=50)),
            ],
        ),
    ]
