# Generated by Django 4.2.2 on 2024-11-23 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerprofile',
            name='phone_number',
            field=models.CharField(default=0, max_length=15, unique=True),
        ),
        migrations.AddField(
            model_name='farmerprofile',
            name='phone_number',
            field=models.CharField(default=0, max_length=15, unique=True),
        ),
    ]
