# Generated by Django 4.2.2 on 2024-11-23 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_alter_customerprofile_phone_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerprofile',
            name='phone_number',
            field=models.CharField(default='0000000000', max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='farmerprofile',
            name='phone_number',
            field=models.CharField(default='0000000000', max_length=15, unique=True),
        ),
    ]
