# Generated by Django 4.2.2 on 2024-11-23 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_alter_customerprofile_phone_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerprofile',
            name='phone_number',
            field=models.CharField(default='Unknown', max_length=15),
        ),
        migrations.AlterField(
            model_name='farmerprofile',
            name='phone_number',
            field=models.CharField(default='Unknown', max_length=15),
        ),
    ]
