# Generated by Django 4.2.2 on 2024-11-23 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_alter_customerprofile_phone_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerprofile',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='farmerprofile',
            name='phone_number',
        ),
    ]
